version: 2.1
jobs:
  run-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.27.1-focal
    # Steps to the job
    steps:
      - checkout
      - run:
          name: Download dependency
          command: npm ci
      - run:
          name: Run tests
          command: npm run test
          environment:
            USERNAME: ${{ secrets.PLAYWRIGHT_USERNAME }}
            PASSWORD: ${{ secrets.PLAYWRIGHT_PASSWORD }}
      - store_test_results:
          path: results.xml

# Invoke jobs via workflows
workflows:
  run-test-workflow:
    jobs:
      - run-test:
          environment:
            PLAYWRIGHT_USERNAME: ${{ secrets.PLAYWRIGHT_USERNAME }}
            PLAYWRIGHT_PASSWORD: ${{ secrets.PLAYWRIGHT_PASSWORD }}
